kind: pipeline
name: build yanic

steps:
- name: backend
  image: golang
  commands:
    - go get
    - go build
    - go test

- name: docker  
  image: plugins/docker
  settings:
    repo: thunderstorm99/yanic
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
